### PR TITLE
[vcpkg baseline] [vs-yasm] Build yasm instead of downloading it to work around memory corruption bugs in yasm itself.

### LINKED ISSUE #12237: [gmp:x64-windows] build failure
**Host Environment**
- OS: [Microsoft Windows [Version 10.0.19041.331]]
- Compiler: Visual Studio 2019 Version: 16.6.3  VS Tools Version: 14.26.28801 

**To Reproduce**
`SYSTEM@ANDROMEDA 07/02/2020 21:20:49 D:\Git\vs2019.prod`
`->vcpkg install gmp[core]:x64-windows nettle[core]:x64-windows`

Additionally, attach any relevant sections from the log files above.

**Failure logs** 
- Cut and past the appropriate build messages from the console output.
`Computing installation plan...`
`The following packages will be built and installed:`
`    gmp[core]:x64-windows`
`    nettle[core]:x64-windows`
`Starting package 1/2: gmp:x64-windows`
`Building package gmp[core]:x64-windows...`
`-- Using cached D:/Git/vcpkg.downloads/ShiftMediaProject-gmp-e140dfc8668e96d7e56cbd46467945adcc6b3cc4.tar.gz`
`-- Extracting source D:/Git/vcpkg.downloads/ShiftMediaProject-gmp-e140dfc8668e96d7e56cbd46467945adcc6b3cc4.tar.gz`
`-- Applying patch vs.build.patch`
`-- Applying patch runtime.patch`
`-- Applying patch prefix.patch`
`-- Using source at D:/Git/vs2019.prod/buildtrees/gmp/src/adcc6b3cc4-2b6258d695`
`-- Building SMP/libgmp.sln for Release`
`-- Building SMP/libgmp.sln for Debug`
`-- Installing: D:/Git/vs2019.prod/packages/gmp_x64-windows/share/gmp/copyright`
`CMake Error at ports/gmp/portfile.cmake:61 (file):`
`  file RENAME failed to rename`

`    D:/Git/vs2019.prod/buildtrees/gmp/x64-windows-rel/adcc6b3cc4-2b6258d695/msvc/include`

`  to`

`    D:/Git/vs2019.prod/packages/gmp_x64-windows/include`

`  because: File exists`

`Call Stack (most recent call first):`
`  scripts/ports.cmake:76 (include)`

`Error: Building package gmp:x64-windows failed with: BUILD_FAILED`
`Please ensure you're using the latest portfiles with `.\vcpkg update`, then`
`submit an issue at https://github.com/Microsoft/vcpkg/issues including:`
`  Package: gmp:x64-windows`
`  Vcpkg version: 2020.02.04-nohash`

- Please attach any additional failure logs mentioned in the console output.
See #11238

**Additional context**
It appears gmp is trying to install its header (include) files in `<vcpkg-root>\installed\x64-windows\include\include` -- which fails because I also have the LLGL port installed and it also has installed its header (include) files into `<vcpkg-root>\installed\x64-windows\include\include\LLGL` (a separate issue I will submit under a separate issue. 

Both are incorrect, I believe the gmp port files should just be in the `<vcpkg-root>\install\x64-windows\include` and LLGL port should be in `<vcpkg-port>\installed\x64-windows\include\LLGL`.

In other words there is one too many `include` in the file destination paths.

### PR DESCRIPTION
**Pull request by BillyONeal**
Works around yasm/yasm#153 .

Should resolve #12237 .

### CODE REVIEW

**Comment by strega-nil** [comment]
This seems like an issue for cross-compilation; have you considered the fallout there?

**Comment by BillyONeal** [comment]
@strega-nil Yes, but I don't see another way. We can't be shipping ports which fail every 2 seconds because their build tools have memory corruption bugs.

**Comment by strega-nil** [comment]
hm. I don't like it but yeah, you're right.

We seriously need to ship tool ports.

File: toolsrc/src/vcpkg/base/files.cpp [hunk 1]
```diff
@@ -1277,6 +1267,7 @@ namespace vcpkg::Files
 #ifdef _WIN32
     fs::path win32_fix_path_case(const fs::path& source)
     {
+        using fs::is_slash;
```
Comment (ras0219) [inline toolsrc/src/vcpkg/base/files.cpp:1270]:
```suggestion
```
since the use below is qualified?

File: ports/yasm-tool/portfile.cmake [hunk 2]
```diff
@@ -0,0 +1,37 @@
+vcpkg_fail_port_install(MESSAGE "The yasm-tool port currently only supports Windows" ON_TARGET "Linux" "OSX" ON_ARCH "x64" "arm")
```
Comment (ras0219) [inline ports/yasm-tool/portfile.cmake:1]:
```suggestion
vcpkg_fail_port_install(MESSAGE "The yasm-tool port is only intended to be built for x86 Windows" ON_TARGET "Linux" "OSX" ON_ARCH "x64" "arm")
```

File: ports/gmp/portfile.cmake [hunk 3]
```diff
@@ -9,14 +9,15 @@ if(VCPKG_TARGET_IS_WINDOWS)
         REF e140dfc8668e96d7e56cbd46467945adcc6b3cc4 #v6.2.0
```
Comment (ras0219) [inline ports/gmp/portfile.cmake:9]: This is missing a port-version update.

**Review by ras0219 — APPROVED** [review]
LGTM once comments are addressed

File: ports/gmp/portfile.cmake (hunk 3 above)
Comment (BillyONeal) [reply ports/gmp/portfile.cmake:9]: That was intentional because there are no changes in the output but...

File: toolsrc/src/vcpkg/base/files.cpp (hunk 1 above)
Comment (BillyONeal) [reply toolsrc/src/vcpkg/base/files.cpp:1270]: The use below is not qualified:

`if (last - first >= 3 && is_slash(first[0]) && is_slash(first[1]) && !is_slash(first[2]))`

GitHub's review tool failed you.
