### PR TITLE
[vcpkg] Fix issue #9781 by exporting from the installed directory

### LINKED ISSUE #9781: vcpkg export requires packages directory
**Describe the bug**
The `vcpkg export` command fails if the `packages` directory (under the vcpkg root directory) does not contain the to-be-exported package. If you `vcpkg install` a package with the `--clean-after-build` switch, the `packages` directory is not going to be present after a successful install.

**Environment**
- OS: Windows 10
- Compiler: Microsoft Visual Studio Professional 2017 Version 15.9.16

**To Reproduce**
Using the `flatbuffers` library as an example, _**you can use any other libraries if you want, the results should be the same**_. Example steps to reproduce the behavior with a `x64-windows` triplet (the triplet itself is irrelevant):
1. `.\vcpkg remove flatbuffers:x64-windows`
2. `.\vcpkg install flatbuffers:x64-windows --clean-after-build`
3. `.\vcpkg export flatbuffers:x64-windows --raw --output="vcpkg-export-flatbuffers"`
4. See error `Source directory C:/workspace/vcpkg/packages/flatbuffers_x64-windows does not exist` (assuming your vcpkg root is at `C:/workspace/vcpkg`).

Results are the same with any of the other export types: "--nuget --ifw --zip --7zip".

**Expected behavior**
The `vcpkg export` command in the above should succeed even if the `packages` directory is not present in the vcpkg root directory. If you omit the `--clean-after-build` switch (`packages` directory remains intact), the export command succeeds:
1. `.\vcpkg remove flatbuffers:x64-windows`
2. `.\vcpkg install flatbuffers:x64-windows`
3. `.\vcpkg export flatbuffers:x64-windows --raw --output="vcpkg-export-flatbuffers"`

**Failure logs** 
```
c:\workspace\vcpkg>vcpkg export flatbuffers:x64-windows --raw --output="vcpkg-export-flatbuffers"
The following packages are already built and will be exported:
    flatbuffers:x64-windows
Exporting package flatbuffers:x64-windows...
Source directory C:/workspace/vcpkg/packages/flatbuffers_x64-windows does not exist
```

**Additional context**
I do not think that the `packages` directory should be necessary to perform a successful export operation. The `installed` directory in the vcpkg root directory has all the necessary information (assuming `x64-windows` triplet for the sake of an example):
- The `installed/x64-windows` directory has all the installed binaries and headers at one place.
- The `*_x64-windows.list` files under `installed/vcpkg/info` have all the information describing what files in the `installed/x64-windows` directory belong to a given library. 

E.g. on my machine right now, the `installed/vcpkg/info/flatbuffers_1.11.0-1_x64-windows.list` file contains the following:
```
x64-windows/
x64-windows/debug/
x64-windows/debug/lib/
x64-windows/debug/lib/flatbuffers.lib
x64-windows/include/
x64-windows/include/flatbuffers/
x64-windows/include/flatbuffers/base.h
x64-windows/include/flatbuffers/code_generators.h
x64-windows/include/flatbuffers/flatbuffers.h
x64-windows/include/flatbuffers/flatc.h
x64-windows/include/flatbuffers/flexbuffers.h
x64-windows/include/flatbuffers/grpc.h
x64-windows/include/flatbuffers/hash.h
x64-windows/include/flatbuffers/idl.h
x64-windows/include/flatbuffers/minireflect.h
x64-windows/include/flatbuffers/reflection.h
x64-windows/include/flatbuffers/reflection_generated.h
x64-windows/include/flatbuffers/registry.h
x64-windows/include/flatbuffers/stl_emulation.h
x64-windows/include/flatbuffers/util.h
x64-windows/lib/
x64-windows/lib/flatbuffers.lib
x64-windows/share/
x64-windows/share/flatbuffers/
x64-windows/share/flatbuffers/FlatbuffersConfig.cmake
x64-windows/share/flatbuffers/FlatbuffersConfigVersion.cmake
x64-windows/share/flatbuffers/FlatbuffersTargets-debug.cmake
x64-windows/share/flatbuffers/FlatbuffersTargets-release.cmake
x64-windows/share/flatbuffers/FlatbuffersTargets.cmake
x64-windows/share/flatbuffers/FlatcTargets-debug.cmake
x64-windows/share/flatbuffers/FlatcTargets-release.cmake
x64-windows/share/flatbuffers/FlatcTargets.cmake
x64-windows/share/flatbuffers/copyright
x64-windows/share/flatbuffers/vcpkg_abi_info.txt
x64-windows/tools/
x64-windows/tools/flatbuffers/
x64-windows/tools/flatbuffers/flatc.exe
```

### PR DESCRIPTION
**Pull request by ras0219**
Currently, `vcpkg export` reads the files out of the `packages\` directory for a given package. This is both
1. Inconvenient, because it prevents --clean-after-build
2. Wrong, since the packages folder is not as tightly controlled by our API surface as the installed directory

Instead, it should read the files from the installed directory (using the listfile as a manifest).

- What does your PR fix?
Fixes #9781 partially (for the core exporters)

### CODE REVIEW

File: toolsrc/include/vcpkg/install.h [hunk 1]
```diff
@@ -71,6 +71,12 @@ namespace vcpkg::Install
     std::vector<std::string> get_all_port_names(const VcpkgPaths& paths);
 
     void install_files_and_write_listfile(Files::Filesystem& fs, const fs::path& source_dir, const InstallDir& dirs);
```
Comment (BillyONeal) [inline toolsrc/include/vcpkg/install.h:73]: This overload set doesn't really make sense now -- an overload adding a parameter somewhere in the middle is unusual. Do these really do the same thing or should they have different names?

File: toolsrc/src/vcpkg/export.cpp [hunk 2]
```diff
@@ -512,7 +511,15 @@ namespace vcpkg::Export
                 action.spec.triplet().to_string(),
                 raw_exported_dir_path / "installed" / "vcpkg" / "info" / (binary_paragraph.fullstem() + ".list"));
 
-            Install::install_files_and_write_listfile(paths.get_filesystem(), paths.package_dir(action.spec), dirs);
+            auto lines = fs.read_lines(paths.listfile_path(binary_paragraph)).value_or_exit(VCPKG_LINE_INFO);
+            std::vector<fs::path> files;
+            for (auto&& suffix : lines)
+            {
+                if (!suffix.empty() && suffix.back() == '\r') suffix.pop_back();
```
Comment (BillyONeal) [inline toolsrc/src/vcpkg/export.cpp:518]: What about `\n`?

Comment (BillyONeal) [reply toolsrc/src/vcpkg/export.cpp:518]: It seems like read_lines should be doing this, not here.

File: toolsrc/src/vcpkg/install.cpp [hunk 3]
```diff
@@ -45,17 +45,25 @@ namespace vcpkg::Install
...
+    void install_files_and_write_listfile(Files::Filesystem& fs,
+                                          const fs::path& source_dir,
+                                          const std::vector<fs::path>& files,
+                                          const InstallDir& destination_dir)
     {
         std::vector<std::string> output;
         std::error_code ec;
 
-        const size_t prefix_length = source_dir.native().size();
+        const size_t prefix_length = source_dir.generic_u8string().size();
```
Comment (BillyONeal) [inline toolsrc/src/vcpkg/install.cpp:62]: This is now an encoding and format conversion; the result of `generic_u8string` should be stored in a variable and reused below (and `source_dir` should become unreferenced).

File: toolsrc/src/vcpkg/install.cpp [hunk 4]
```diff
@@ -45,17 +45,25 @@ namespace vcpkg::Install
     void install_files_and_write_listfile(Files::Filesystem& fs,
                                           const fs::path& source_dir,
                                           const InstallDir& destination_dir)
+    {
+        Checks::check_exit(
```
Comment (BillyONeal) [inline toolsrc/src/vcpkg/install.cpp:49]: Why does this overload get that validation but not the other one?

File: toolsrc/src/vcpkg/install.cpp [hunk 5]
```diff
@@ -45,17 +45,25 @@ namespace vcpkg::Install
...
+            VCPKG_LINE_INFO, fs.exists(source_dir), "Source directory %s does not exist", source_dir.generic_string());
```
Comment (BillyONeal) [inline toolsrc/src/vcpkg/install.cpp:50]: Given that this is a user facing string we should match what they typed when possible so this should use `string()` rather than `generic_string()` (or if check_exit expects UTF-8 it should be `generic_u8string`)

File: toolsrc/src/vcpkg/install.cpp (hunk 4 above)
Comment (ras0219) [reply toolsrc/src/vcpkg/install.cpp:49]: This overload actually uses source_dir to enumerate files; the other overload is only using its formatted length to strip the prefix.

File: toolsrc/src/vcpkg/install.cpp (hunk 3 above)
Comment (ras0219) [reply toolsrc/src/vcpkg/install.cpp:62]: Due to the particulars of how the prefix is being removed (via substring instead of using relative path computations), I think it's best to call this inside this function so that it is obviously matching the same specific conversion below (`file.generic_u8string()`). `source_dir` is not otherwise used in this function, so there is no need to store the temporary.

File: toolsrc/src/vcpkg/export.cpp (hunk 2 above)
Comment (ras0219) [reply toolsrc/src/vcpkg/export.cpp:518]: Turns out read_lines was already doing exactly this

File: toolsrc/include/vcpkg/install.h (hunk 1 above)
Comment (ras0219) [reply toolsrc/include/vcpkg/install.h:73]: Renamed.

File: toolsrc/src/vcpkg/install.cpp (hunk 5 above)
Comment (ras0219) [reply toolsrc/src/vcpkg/install.cpp:50]: Changed to `u8string()`

**Review by BillyONeal — APPROVED** [review]

**Comment by davidebeatrici** [comment]
Thank you very much for creating this!

Unfortunately there's an issue. For each triplet two folders are created instead of one, resulting in:
```
<vcpkg-export>\installed\x64-windows-static-md\x64-windows-static-md
```

Moving the subdirectory's content one level upper (root `x64-windows-static-md`) makes the environment work as expected.

File: toolsrc/src/vcpkg/export.cpp [hunk 6]
```diff
@@ -515,10 +515,14 @@ namespace vcpkg::Export
             std::vector<fs::path> files;
             for (auto&& suffix : lines)
             {
+                if (suffix.empty()) continue;
```
Comment (BillyONeal) [inline toolsrc/src/vcpkg/export.cpp:518]: Isn't that list file under our control? Why not generate the correct content rather than patching it up after the fact?

**Review by JackBoosY — APPROVED** [review]

File: toolsrc/src/vcpkg/export.cpp (hunk 6 above)
Comment (ras0219) [reply toolsrc/src/vcpkg/export.cpp:518]: We have to handle any files that may exist from a previous vcpkg version
