### PR TITLE
Only use prebuilt musl libc binary with x86_64 arch

### LINKED ISSUE #30170: bootstrap.sh downloads x64 binary when run under arm64 Alpine Linux
**Describe the bug**
When bootstrap-vcpkg.sh is executed on an arm64 Alpine Linux host, a `vcpkg` binary for the x86-64 architecture is downloaded.

**Environment**
- OS: Alpine Linux (arm64)
- Compiler: N/A

**To Reproduce**
1. `./bootstrap-vcpkg.sh`
2. `./file vcpkg`
Result:
`vcpkg: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), static-pie linked, stripped`

**Expected behavior**
A vcpkg executable built for ARM aarch64 should be downloaded or built.

**Additional context**
The problem appears to be caused by the following lines in the bootstrap script:
```shell
if [ -e /etc/alpine-release ]; then                                        
    vcpkgUseSystem="ON"                                                                    
    vcpkgUseMuslC="ON"                                                
fi   
```

When `vcpkgUseMuslC` is `ON`, then the following branch is taken:
```shell
elif [ "$vcpkgUseMuslC" = "ON" ]; then                                     
    echo "Downloading vcpkg-muslc..."                                                      
    vcpkgToolReleaseSha="e8e439126c410dd39f4df2fdfc389e0e9e01df6789bfd3e5a16bf88c11a90439a14f84575badfe4f969db6e5c01040207073dc8b93d4f99d6dd18d1b372d9549"
    vcpkgToolName="vcpkg-muslc"  
```

This downloads an x86-64 binary for vcpkg, which can't be run on the aarch64 host platform.

### PR DESCRIPTION
**Pull request by d-ferenczi**
Fixes #30170

As described in https://github.com/microsoft/vcpkg/issues/30170, `bootstrap-vcpkg.sh` currently incorrectly downloads x86_64 binaries for arm hosts, if the host is running alpine linux, regardless of the host architecture.  
This PR fixes this issue, by checking the platform architecture along `/etc/alpine-release`. If the architecture is not x86_64, it will default to compiling the source, as it already happens on other distributions, e.g. ubuntu.

### CODE REVIEW

**Comment by jimwang118** [comment]
Thank you for mentioning this PR, our ci does not have a corresponding machine to test this change, so please make sure that the local test is ok.

File: scripts/bootstrap.sh [hunk 1]
```diff
@@ -93,7 +93,7 @@ vcpkgCheckRepoTool tar
 UNAME="$(uname)"
 ARCH="$(uname -m)"
 
-if [ -e /etc/alpine-release ]; then
+if [ -e /etc/alpine-release -a "$ARCH" = "x86_64" ]; then
     vcpkgUseSystem="ON"
     vcpkgUseMuslC="ON"
 fi
```
Comment (dg0yt) [inline scripts/bootstrap.sh:99]: This change also removes `vcpkgUseSystem="ON"` from non-x86_64. This doesn't seem right to me.

**Review by dg0yt — COMMENTED** [review]
I wonder if the download block wouldn't be better served by a `case` pattern as commonly found in `configure` scripts:
~~~sh
case "${UNAME},${ARCH},${vcpkgUseMuslC}" in
Darwin,*)
...
Linux,x86_64,ON)
...
Linux,x86_64,*)
...
*)
...
esac
~~~
This could be easily extended to support arm, bsd or similar.

File: scripts/bootstrap.sh (hunk 1 above)
Comment (danifv) [reply scripts/bootstrap.sh:99]: When using current vcpkg, I get the following message if I try bootstrapping on an alpine host, that lacks the required packages:
```
./vcpkg/bootstrap-vcpkg.sh -disableMetrics
On Alpine:
  apk add build-base cmake ninja zip unzip curl git
  (and export VCPKG_FORCE_SYSTEM_BINARIES=1)
```
If I install the required packages, without setting `VCPKG_FORCE_SYSTEM_BINARIES` to 1, and then proceed to installing a package, then I get a note saying, that a suitable version of cmake was not found, which is followed by a download of Kitware/CMake.  
However, if I set `VCPKG_FORCE_SYSTEM_BINARIES=1`, then my system installation of CMake is used, so `vcpkgUseSystem` by itself doesn't seem to have an effect.  

If I bootstrap on aarch64 without `VCPKG_FORCE_SYSTEM_BINARIES`, an x64_86 distribution is downloaded, so not only is `vcpkgUseSystem` without effect, but an incompatible binary is downloaded.  

What is the relation between `VCPKG_FORCE_SYSTEM_BINARIES` and `vcpkgUseSystem`? What is the expected behavoiur?

Comment (jimwang118) [reply scripts/bootstrap.sh:99]: @dg0yt Please help to make sure this modification is correct.

**Comment by jimwang118** [comment]
@danifv Please make sure that this modification only works on `x64` and has no effect on other platforms. If you can confirm that the revision is correct, I will submit the application for integration.

**Comment by danifv** [comment]
> @danifv Please make sure that this modification only works on `x64` and has no effect on other platforms. If you can confirm that the revision is correct, I will submit the application for integration.

I've changed the code, so that `vcpkgUseSystem="ON"` remains set on alpine for all archs.

Otherwise I can confirm, that behaviour on `x64` remains unchanged, and that on other archs a correct binary is compiled instead of an incorrect one being downloaded.

**Comment by BillyONeal** [comment]
Can you help us get instructions on how to build a real arm64 copy so that people can get something to use directly? We would like folks to not have to pay the compilation time to build us but don't have arm64-linux experience ourselves...

**Comment by danifv** [comment]
> Can you help us get instructions on how to build a real arm64 copy so that people can get something to use directly? We would like folks to not have to pay the compilation time to build us but don't have arm64-linux experience ourselves...

Sure! Do you have a pipeline for building the x64 musl binaries? Would this pipeline work on arm64?
We basically did the following on our arm-based build host:
1. patched vcpkg with our custom `bootstrap-vcpkg.sh`
2. upon use a suitable binary was built

**Comment by BillyONeal** [comment]
> Sure! Do you have a pipeline for building the x64 musl binaries?

Yes.

>Would this pipeline work on arm64?

I don't believe so. We don't have arm64 hardware.

**Comment by danifv** [comment]
> > Would this pipeline work on arm64?
> 
> I don't believe so. We don't have arm64 hardware.

Unfortunately I don't have personal access to arm64 hardware, and as far as I've checked github.com actions/gitlab.com runners don't provide arm64 hardware either.
I'm not familiar with your infrastructure, but isn't qemu an option for you? Wouldn't this be easier to set up than to depend on 3rd party builds?

**Comment by BillyONeal** [comment]
>I'm not familiar with your infrastructure, but isn't qemu an option for you? 

I really don't have any idea. (This is kind of a "I lost my yo-yo." "Where did you have it last?" "Hey! If I knew that, I would still have my yo-yo!" situation)
