### PR TITLE
[vcpkg] Correctly record default feature list in BinaryParagraphs. Fixes #10678.

### LINKED ISSUE #10678: Dependency on default-features of a port not respected when dependency already installed
**Describe the bug**

When I install harfbuzz it always installs freetype with configuration [bzip2,core,png] even when I specify [core]. It seems that dependency resolution does not consider manual dependencies specified on command line.

**Environment**
- Windows. 
- Version: e1fc03c47. vcpkg_from_git: Add support for git over ssh

**To Reproduce**
1. vcpkg.exe --triplet x86-windows install freetype[core] harfbuzz[core,ucdn]

Output:
```
  * bzip2[core]:x86-windows
    freetype[bzip2,core,png]:x86-windows
    harfbuzz[core,ucdn]:x86-windows
  * libpng[core]:x86-windows
  * ragel[core]:x86-windows
  * zlib[core]:x86-windows
```

**Expected behavior**

Only install freetype[core] packages:

Expected Output:
```
    freetype[core]:x86-windows
    harfbuzz[core,ucdn]:x86-windows
  * ragel[core]:x86-windows
  * zlib[core]:x86-windows
```

### PR DESCRIPTION
**Pull request by ras0219-msft**
When determining the precise list of features requested by a particular package reference (`FullPackageSpec` in the code), the resolution algorithm must sometimes consult the list of default dependencies for the already installed package. This is because a reference such as `cpprestsdk[compression]` refers to the union of `cpprestsdk`'s declared default features and the `compression` feature. In the case of depending upon an already installed package, we resolve defaults to the _installed package's_ list until that package has been determined to need rebuilding.

Unfortunately, we were silently not recording the list of defaults for packages, which caused all references to default features in already installed packages to misbehave and not actually require any features.

- What does your PR fix?

Fixes an underlying bug discovered in issue #10678. Users will need to rebuild all packages with default features to fully fix the problem. Requires also merging #11082 for a full resolution of @Ghabry's issue.

- Which triplets are supported/not supported? Have you updated the CI baseline?

N/A

- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?

Yes

### CODE REVIEW

File: toolsrc/src/vcpkg/dependencies.cpp [hunk 1]
```diff
@@ -106,15 +106,13 @@ namespace vcpkg::Dependencies
...
+                if (auto vars = maybe_vars.get())
                 {
                     // Qualified dependency resolution is available
-                    auto fullspec_list = filter_dependencies(
-                        *qualified_deps, m_spec.triplet(), maybe_vars.value_or_exit(VCPKG_LINE_INFO));
+                    auto fullspec_list = filter_dependencies(*qualified_deps, m_spec.triplet(), *vars);
 
                     for (auto&& fspec : fullspec_list)
                     {
-                        // TODO: this is incorrect and does not handle default features nor "*"
```
Comment (cbezault) [inline toolsrc/src/vcpkg/dependencies.cpp:117]: Idk this is still kind of gross and defeats the goal of to_feature_specs

**Review by cbezault — APPROVED** [review]

File: toolsrc/src/vcpkg/dependencies.cpp (hunk 1 above)
Comment (ras0219-msft) [reply toolsrc/src/vcpkg/dependencies.cpp:117]: This is removed because it does correctly handle default features (but doesn't handle the undocumented `*` feature).;

Comment (cbezault) [reply toolsrc/src/vcpkg/dependencies.cpp:117]: I still think it's still unfortunate that we have to special case this.

It would be clearer if each feature spec could declare exactly which other feature specs it depends on when it gets processed by this function. Instead we lazily just defer that discovery to the pass of this function which evaluates each of a feature spec's dependencies.

Comment (cbezault) [reply toolsrc/src/vcpkg/dependencies.cpp:117]: I put a fair amount of effort into trying to avoid having either the `*` or `default` features get created as `FeatureSpec`s when doing the dependency resolution to avoid the added complexity they bring along with them.

Comment (cbezault) [reply toolsrc/src/vcpkg/dependencies.cpp:117]: Anyway this PR does what it is supposed to do.
