### PR TITLE
[vcpkg] testing for architectures supported by toolset

### LINKED ISSUE #1684: building bzip2:x86-windows-static out of the box just fails
I'm using visual studio 2015 express.
in config-x86-windows-static-rel.log, I can see

CMake Error at C:/github/vcpkg/scripts/buildsystems/vcpkg.cmake:32 (message):
  Unable to determine target architecture.
Call Stack (most recent call first):
  C:/github/vcpkg/downloads/cmake-3.9.1-win32-x86/share/cmake-3.9/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt:2 (project)

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage

### PR DESCRIPTION
**Pull request by Mixaill**
fix #1684

### CODE REVIEW

File: toolsrc/src/vcpkg_Build.cpp [hunk 1]
```diff
@@ -36,39 +36,35 @@ namespace vcpkg::Build
...
+        static constexpr ToolsetArchOption X86_ARM = {L"x86_arm", CPU::X86, CPU::ARM};
+        static constexpr ToolsetArchOption X86_ARM64 = {L"x86_arm64", CPU::X86, CPU::ARM64};
+
+        static constexpr ToolsetArchOption X64 = {L"amd64", CPU::X64, CPU::X64};
+        static constexpr ToolsetArchOption X64_X86 = {L"amd64_x86", CPU::X64, CPU::X86};
+        static constexpr ToolsetArchOption X64_ARM = {L"amd64_arm", CPU::X64, CPU::ARM};
+        static constexpr ToolsetArchOption X64_ARM64 = {L"amd64_arm64", CPU::X64, CPU::ARM64};
+
+        static constexpr std::array<ToolsetArchOption, 8> VALUES = {
             X86, X86_X64, X86_ARM, X86_ARM64, X64, X64_X86, X64_ARM, X64_ARM64};
```
Comment (Mixaill) [inline toolsrc/src/vcpkg_Build.cpp]: Is it the right order? Maybe we should prefer AMD64?

**Comment by thierryba** [comment]
works like a charm for me.

**Comment by ras0219-msft** [comment]
Thanks for the PR! This looks like a really good approach to the problem.

Changes while merging:
- Since you already record the vcvars selection argument in the `supported_architectures`, I changed the search to only look for Host/Target and then use the string from `supported_architectures`. This also enables different arguments for different vcvars versions, if that ever becomes needed.
- As much as I'd love an ARM-native compiler build, I don't believe any VS version contains one 😄.
