### PR TITLE
[vcpkg] Fix nuget package import failed.

### LINKED ISSUE #11028: NuGet package doesn't add proper include and library paths
**Describe the bug**
I just recently pulled the newest set of ports in order to update all the dependencies in my project. NuGet export needed to update NuGet from 4.6.2 to 4.8.1. I created a package and installed it in my project using the Package Manager Console as I did multiple times before. This time though my project doesn't seem to have proper include and library paths set.

For example if I want to `#include <fmt/format.h>` I will get an error saying `cannot open source file "fmt/format.h"`. It's clear to me that include path is not set. What's curious though is that if I write `#include <../x64-windows/include/fmt/format.h>` it works! I'm not sure what the include path might be though since it's neither `installed/x64-windows` nor `installed/vcpkg`.

If I manually add `packages\MyPackage.1.0.2\installed\x64-windows\include` to the project include paths it works fine, but since I shouldn't be doing this when using NuGet, I don't want to.

Even If I do though the same applies to library path since compiling the project reports a big set of unresolved external errors.

Before that the last time I updated the package was yesterday. That was before pulling from the vcpkg repository, so it seems that updating vcpkg (or NuGet) is a probable cause of the problem.

**Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019 Community 16.5.4, Toolchain v142

**To Reproduce**
1. ./vcpkg install fmt:x64-windows
2. ./vcpkg export fmt:x64-windows --nuget
3. Install the package in a project
4. `#include <fmt/format.h>` reports an error saying `cannot open source file "fmt/format.h"`

**Expected behavior**
I expect installing a NuGet package to setup proper include and library paths as it did before.

**Additional context**

- It happens on my project and on a clean one
- It happens if I export all the dependencies and when I only export one of them
- I don't use vcpkg integration and always export NuGet packages
- I set my projects to the appropriate architecture when testing
- I'm currently on vcpkg master@28ab0b1

### PR DESCRIPTION
**Pull request by shihaonan369**
**Describe the pull request**
Fix nuget package import failed.
- What does your PR fix? Fixes #11028 
- Which triplets are supported/not supported? Have you updated the CI baseline?
All of triplets, CI baseline not updated.
- Does your PR follow the [maintainer guide](https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/maintainer-guide.md)?
Yes

### CODE REVIEW

**Review by Cheney-W — APPROVED** [review]

**Comment by strega-nil** [comment]
Hey @ras0219-msft, does this look correct? I don't know anything about nuget, unfortunately.

File: toolsrc/src/vcpkg/export.cpp [hunk 1]
```diff
@@ -62,7 +62,7 @@ namespace vcpkg::Export
         return Strings::format(R"###(
 <Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
   <PropertyGroup>
-    <VcpkgRoot>$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory), .vcpkg-root))\installed\$(VcpkgTriplet)\</VcpkgRoot>
+    <VcpkgRoot></VcpkgRoot>
```
Comment (dan-shaw) [inline toolsrc/src/vcpkg/export.cpp:65]: I'm not too familiar with this, but it seems that this variable is not set - would it make sense to remove it instead?

Comment (shihaonan369) [reply toolsrc/src/vcpkg/export.cpp:65]: It can be set in vcpkg.targets.
