### PR TITLE
[vcpkg] Improve error messages for incomplete Mono

### LINKED ISSUE #14784: vcpkg Linux nuget export failure
**Host Environment**
- OS: Linux running in WSL on Windows
- Note: this is a vcpkg repo created on the Windows side (at c:\repos\vcpkg) and accessed inside WSL in-place (at /mnt/c/repos/vcpkg).  However I also tried cloning the repo completely inside Linux and the exact same error happens.

**To Reproduce**
```
sudo apt install nuget
./bootstrap-vcpkg.sh
export VCPKG_DEFAULT_TRIPLET=x64-linux
export VCPKG_PLATFORM_TOOLSET=v142
./vcpkg install eigen3:x64-linux ceres[eigensparse]:x64-linux opencv3:x64-linux ffmpeg[ffmpeg]:x64-linux
./vcpkg export eigen3:x64-linux ceres[eigensparse]:x64-linux opencv3:x64-linux ffmpeg[ffmpeg]:x64-linux --nuget --nuget-id=VcpkgFetchedDependencies.x64-linux --nuget-version=1.0.0
```
**Failure logs** 
Everything succeeds until I get to the export.
```
sloh@SLOH-LAPTOP2:/mnt/c/repos/vcpkg$ ./vcpkg export eigen3:x64-linux ceres[eigensparse]:x64-linux opencv3:x64-linux ffmpeg[ffmpeg]:x64-linux --nuget --nuget-id=Calibration.VcpkgFetchedDependencies.x64-linux --nuget-version=1.0.0
The following packages are already built and will be exported:
    ceres:x64-linux
[various packages removed]
  * zlib:x64-linux
Additional packages (*) need to be exported to complete this operation.
Exporting package eigen3:x64-linux...
[various packages removed]
Exporting package ffmpeg:x64-linux...
Packing nuget package...
A suitable version of nuget was not found (required v5.5.1). Downloading portable nuget v5.5.1...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v5.5.1/nuget.exe -> /mnt/c/repos/vcpkg/downloads/22ea847d-nuget.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6359k  100 6359k    0     0  8367k      0 --:--:-- --:--:-- --:--:-- 8400k
Value was null
```
As you see above, I've already done `sudo apt install nuget`.  `sudo apt-get install nuget=5.5.1` says there is no such version.  And I don't think it should be looking for a "win-x86-commandline" version.  I'm running Linux inside WSL on a 64-bit machine. 
 Is this something about running inside WSL?

For whatever it's worth, I *am* able to export a zip.

### PR DESCRIPTION
**Pull request by ras0219**
This PR fixes #14784 by providing better error information when the user has an incomplete mono installation (i.e. just `mono-runtime` instead of `mono-complete`). It also partially improves #14304 for Ubuntu 18.04 users, noting that they will need to get a newer version of `mono` than is available in apt.

#### Example 1
Before:
>root@0b923fc8e7fa:/vcpkg# ./vcpkg export --nuget zlib:x86-windows
The following packages are already built and will be exported:
    zlib:x86-windows
Exporting package zlib:x86-windows...
Packing nuget package...
Could not automatically acquire mono because there is no entry in /vcpkg/scripts/vcpkgTools.xml for os=linux. You may be able to install mono via your system package manager.

After
>root@0b923fc8e7fa:/vcpkg# ./vcpkg.new export --nuget zlib:x86-windows
The following packages are already built and will be exported:
    zlib:x86-windows
Exporting package zlib:x86-windows...
Packing nuget package...
Could not automatically acquire mono because there is no entry in /vcpkg/scripts/vcpkgTools.xml for os=linux. You may be able to install mono via your system package manager (e.g. sudo apt install mono-complete). Ubuntu 18.04 users may need a newer version of mono, available at https://www.mono-project.com/download/stable/.

#### Example 2
Before:
>root@0b923fc8e7fa:/vcpkg# ./vcpkg export --nuget zlib:x86-windows
The following packages are already built and will be exported:
    zlib:x86-windows
Exporting package zlib:x86-windows...
Packing nuget package...
A suitable version of nuget was not found (required v5.5.1). Downloading portable nuget v5.5.1...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v5.5.1/nuget.exe -> /vcpkg/downloads/22ea847d-nuget.exe
Value was null

After:
>root@0b923fc8e7fa:/vcpkg# ./vcpkg.new export --nuget zlib:x86-windows
The following packages are already built and will be exported:
    zlib:x86-windows
Exporting package zlib:x86-windows...
Packing nuget package...
A suitable version of nuget was not found (required v5.5.1). Downloading portable nuget v5.5.1...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v5.5.1/nuget.exe -> /vcpkg/downloads/22ea847d-nuget.exe
Failed at [../src/vcpkg/tools.cpp(236)] with message:
Could not load file or assembly 'System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
System.IO.FileNotFoundException: Could not load file or assembly 'System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.ComponentModel.Composition, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
  at NuGet.CommandLine.Program.MainCore (System.String workingDirectory, System.String[] args) [0x000d8] in <94d83393be9c41c48c8dff90a7cc668d>:0
>
>
>Failed to get version of /vcpkg/downloads/tools/nuget-5.5.1-linux/nuget.exe
This may be caused by an incomplete mono installation. Full mono is available on some systems via `sudo apt install mono-complete`. Ubuntu 18.04 users may need a newer version of mono, available at https://www.mono-project.com/download/stable/

### CODE REVIEW

**Review by vicroms — APPROVED** [review]

File: toolsrc/include/vcpkg/base/expected.h [hunk 1]
```diff
@@ -110,7 +110,10 @@ namespace vcpkg
         // Constructors are intentionally implicit
 
         ExpectedT(const S& s, ExpectedRightTag = {}) : m_s(s) { }
-        ExpectedT(S&& s, ExpectedRightTag = {}) : m_s(std::move(s)) { }
+        template<class = std::enable_if<!std::is_reference<S>::value>>
```
Comment (BillyONeal) [inline toolsrc/include/vcpkg/base/expected.h:113]: If `S` can be a reference something is seriously broken here because that makes `const S&` above do the wrong thing for it, etc.

Comment (ras0219-msft) [reply toolsrc/include/vcpkg/base/expected.h:113]: The issue was that this constructor was being preferred over the `ExpectedLeftTag` move construtor, so if you had:
```cpp
ExpectedS<std::string> foo() {
  return std::string("hello, world!");
}
```
it would successfully compile with "hello, world!" as the _error_ message. I added this clause to be symmetric with the other constructor so that this pattern would fail to compile so the programmer will explicitly disambiguate with
```cpp
return {"hello, world!", expected_left_tag};
```

Comment (BillyONeal) [reply toolsrc/include/vcpkg/base/expected.h:113]: I'm totally on board with adding this ctor, but I think the enable_if is unnecessary. (And if the enable_if *is* necessary, then something elsewhere is busted)

Comment (BillyONeal) [reply toolsrc/include/vcpkg/base/expected.h:113]: To be clear, that would only engage if someone declares `ExpectedS<T&>`; here `S` is the class template type parameter, not anything deduced, so there's no reference deduction going on.

Comment (ras0219) [reply toolsrc/include/vcpkg/base/expected.h:113]: Meaning you'd prefer it as `template<class=void>`?

Comment (BillyONeal) [reply toolsrc/include/vcpkg/base/expected.h:113]: I guess the way in which this is totally broken was preexisting so I'll widthdraw this objection for now :(

**Review by BillyONeal — APPROVED** [review]

File: toolsrc/include/vcpkg/base/expected.h (hunk 1 above)
Comment (BillyONeal) [reply toolsrc/include/vcpkg/base/expected.h:113]: http://eel.is/c++draft/dcl.ref#6 I stand corrected on how the `const S&` collapses here so it isn't actually hopelessly broken as I thought anyway.
