### PR TITLE
[vcpkg] Harden file removals and clean directory contents in "CI" inside vcpkg itself.

### LINKED ISSUE #11395: initialize-environment.ps1 failing windows builds
**Describe the bug**
All my latest pull requests requests failing on windows during environment initialization:

https://dev.azure.com/vcpkg/public/_build/results?buildId=36974&view=logs&j=878666d5-db33-5b27-9e7d-b0c7ee352005&t=74aefe2a-c21b-52a4-9295-f464e377cc01&l=28
```
Linking downloads => D:\downloads
##[error]C:\agent\_work\1\s\scripts\azure-pipelines\windows\initialize-environment.ps1 : Exception calling "Delete" with "1" 
##[error]argument(s): "The directory is not empty.
"
At C:\agent\_work\_temp\f631f658-541a-4f38-b5be-3d80e71b5a09.ps1:3 char:1

##[error]+ . 'C:\agent\_work\1\s\scripts\azure-pipelines\windows\initialize-envi ...

##[error]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

##[error]    + CategoryInfo          : NotSpecified: (:) [initialize-environment.ps1], MethodInvocationException

##[error]    + FullyQualifiedErrorId : IOException,initialize-environment.ps1

##[error] 

##[error]PowerShell exited with code '1'.
```
And I see the same error in other PRs too - https://dev.azure.com/vcpkg/public/_build/results?buildId=36980&view=logs&j=3859ca13-59fe-57bd-13f9-449df7d191a6&t=cca7a5dc-b423-5664-9a84-dcceb853785f&l=39

### PR DESCRIPTION
**Pull request by BillyONeal**
`files.h/files.cpp`:
* Add end and else comments to all macros.
* Add "remove_all_inside" function which empties a directory without actually deleting the directory. This is necessary to handle the case where the directory is actually a directory symlink.
* Change remove_all to use std::remove when VCPKG_USE_STD_FILESYSTEM is set; this will engage POSIX delete support available on current Win10.

`commands.ci.cpp`: empty "installed".

`*/initialize_environment.*`: No longer clean the directories outside the tool.

`ci-step.ps1`: Remove unused console output tee-ing.

Fixes #11395 (hopefully)

### CODE REVIEW

File: toolsrc/src/vcpkg/base/files.cpp [hunk 1]
```diff
@@ -651,6 +684,59 @@ namespace vcpkg::Files
...
+                    {
+                        return; // keep inner failure_point
+                    }
+                }
+                else
+                {
+                    this->remove(thisPath, ec);
+                }
+
+                if (ec)
```
Comment (BillyONeal) [inline toolsrc/src/vcpkg/base/files.cpp:725]: Goes inside preceding else

File: scripts/azure-pipelines/osx/initialize-environment.sh [hunk 2]
```diff
@@ -4,29 +4,20 @@
 
 # Sets up the environment for MacOS runs of vcpkg CI
 
-rm -rf installed || true
```
Comment (strega-nil) [inline scripts/azure-pipelines/osx/initialize-environment.sh:7]: Is this okay? Don't we still need to remove this before `vcpkg ci`?

**Review by strega-nil — APPROVED** [review]

File: scripts/azure-pipelines/osx/initialize-environment.sh (hunk 2 above)
Comment (BillyONeal) [reply scripts/azure-pipelines/osx/initialize-environment.sh:7]: No, this change makes the ci command do that: https://github.com/microsoft/vcpkg/pull/11432/files#diff-2b467942d4ff71ffedfb2c0396ee333dR401
