### PR TITLE
[bootstrap-vcpkg.sh] Test for ${CC} rather than gcc on systems using vcpkgUseSystem

### LINKED ISSUE #36807: On OpenBSD, do not require "gcc" to be installed
**Describe the bug**
Currently, the [vcpkg boostrap logic has a branch](https://github.com/microsoft/vcpkg/blob/13bde2ff13192e1b2fdd37bd9b475c7665ae6ae5/scripts/bootstrap.sh#L103) for OpenBSD where the C and C++ compilers are set to clang. In addition, the `vcpkgUseSystem` flag is set to ON. 

[A few lines later](https://github.com/microsoft/vcpkg/blob/13bde2ff13192e1b2fdd37bd9b475c7665ae6ae5/scripts/bootstrap.sh#L114), the `vcpkgUseSystem` being ON causes a [hard dependency on gcc](https://github.com/microsoft/vcpkg/blob/13bde2ff13192e1b2fdd37bd9b475c7665ae6ae5/scripts/bootstrap.sh#L118), despite OpenBSD using clang whether gcc is installed or not. This check will fail, because [the gcc binary is called egcc by default on OpenBSD](https://github.com/openbsd/ports/blob/575cada68bd4b2a0450c358d6991a6f57d517b82/lang/gcc/11/pkg/PLIST-main#L5) .

**Environment**
- OS: OpenBSD vultr.guest 7.4 GENERIC.MP#2 amd64
- Compiler: clang version 16.0.6

**To Reproduce**
1. sh boostrap-vcpkg.sh
2. See error
Repro code when

**Expected behavior**
As the `CC` and `CXX` environment variables are provided at this point, just pass them to `cmake` and skip the "check" for gcc. 

**Failure logs**

**Additional context**

### PR DESCRIPTION
**Pull request by SchaichAlonso**
Fixes #36807

### CODE REVIEW

File: scripts/bootstrap.sh [hunk 1]
```diff
@@ -98,24 +98,22 @@ if [ -e /etc/alpine-release ]; then
...
+    CXX=${CXX:=clang++}
 fi
 
 if [ "$vcpkgUseSystem" = "ON" ]; then
     vcpkgCheckRepoTool cmake
     vcpkgCheckRepoTool ninja
     vcpkgCheckRepoTool git
-    vcpkgCheckRepoTool gcc
+    vcpkgCheckRepoTool ${CC}
+    vcpkgCheckRepoTool ${CXX}
```
Comment (dg0yt) [inline scripts/bootstrap.sh:116]: I think this is to early.
There is the legacy gcc cascade starting at line 196. Legacy because it should be remove for simply using gcc and g++.
After this choice, there should be the vcpkgCheckRepoTool for CC/CXX.

And BTW can't we simply use `cc` / `c++`, instead of favoring particular vendors?

Comment (SchaichAlonso) [reply scripts/bootstrap.sh:116]: From a logical perspective, it is too early. Alphine Linux systems require `gcc` to be installed but might later on decide to use `gcc-12` instead, making the `gcc` requirement obsolete.

Using cc and c++ as default values for `CC` and `CXX` is probably more straightforward then manually enforcing gcc or clang. Users that aren't happy with their system's default compiler probably export `CC`/`CXX` system-wide anyways.

The version selection for gcc is quite fishy, anyways. Distributors deciding to install gcc with some suffixes usually also patch their cmake package to detect the suffixed gcc, so the whole cascade can be dropped as cmake will do the right thing anyways, while our manual preference setup lacks a branch for gcc-13 which "most likely" should be prefered over gcc-6.

Comment (dg0yt) [reply scripts/bootstrap.sh:116]: > The version selection for gcc is quite fishy, anyways. 

This was discussed before, and there is support for removing it. Just nobofy did it...

Comment (SchaichAlonso) [reply scripts/bootstrap.sh]: I'll remove it then

**Review by dg0yt — APPROVED** [review]
LGTM.
Let's see what vcpkg team says.

**Comment by jimwang118** [comment]
The test script runs correctly on Linux. Add reviewed tag for further review by the vcpkg team.

File: scripts/bootstrap.sh [hunk 2]
```diff
@@ -197,27 +189,6 @@ fi
 if [ "$vcpkgDownloadTool" = "ON" ]; then
     vcpkgDownloadFile "https://github.com/microsoft/vcpkg-tool/releases/download/$VCPKG_TOOL_RELEASE_TAG/$vcpkgToolName" "$vcpkgRootDir/vcpkg" $vcpkgToolReleaseSha
 else
-    if [ "x$CXX" = "x" ]; then
```
Comment (BillyONeal) [inline scripts/bootstrap.sh:200]: For what it's worth, I believe this stuff was here to deal with when we needed `std::filesystem` and the compilers on the other platforms. I think on the platforms where this was needed we now provide binaries so I'm happy with removing it; but strictly speaking it seems unrelated to the slated issue...
