### PR TITLE
[vcpkg] use UTF-8 for console input/output

### LINKED ISSUE #1631: Error: Building package libepoxy:x86-windows failed with: BUILD_FAILED
I performed ".\vcpkg update" and then ".\vcpkg install gtk". The output was:

>The following packages will be built and installed:
>    gtk:x86-windows
>  \* libepoxy:x86-windows
>Additional packages (*) will be installed to complete this operation.
>Building package libepoxy:x86-windows...
>-- CURRENT_INSTALLED_DIR=C:/Program Files (x86)/vcpkg/vcpkg/installed/x86-windows
>-- DOWNLOADS=C:/Program Files (x86)/vcpkg/vcpkg/downloads
>-- CURRENT_PACKAGES_DIR=C:/Program Files (x86)/vcpkg/vcpkg/packages/libepoxy_x86-windows
>-- CURRENT_BUILDTREES_DIR=C:/Program Files (x86)/vcpkg/vcpkg/buildtrees/libepoxy
>-- CURRENT_PORT_DIR=C:/Program Files (x86)/vcpkg/vcpkg/ports/libepoxy/.
>-- Using cached C:/Program Files (x86)/vcpkg/vcpkg/downloads/anholt-libepoxy-1.4.3.tar.gz
>-- Testing integrity of cached file...
>-- Testing integrity of cached file... OK
>-- Extracting done
>-- Configuring x86-windows-rel
>CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
>    Command failed: C:/Program Files (x86)/vcpkg/vcpkg/downloads/tools/python/python.exe;C:/Program Files (x86)/vcpkg/vcpkg/downloads/tools/meson/meson-0.40.1/meson.py;-Denable-glx=no;-Denable-egl=no;--buildtype;plain;--backend;ninja;--default-library;shared;--prefix;C:/Program Files (x86)/vcpkg/vcpkg/packages/libepoxy_x86-windows;C:/Program Files (x86)/vcpkg/vcpkg/buildtrees/libepoxy/src/libepoxy-1.4.3
>    Working Directory: C:/Program Files (x86)/vcpkg/vcpkg/buildtrees/libepoxy/x86-windows-rel
>    See logs for more information:
>      C:\Program Files (x86)\vcpkg\vcpkg\buildtrees\libepoxy\config-x86-windows-rel-out.log
>      C:\Program Files (x86)\vcpkg\vcpkg\buildtrees\libepoxy\config-x86-windows-rel-err.log
>
>Call Stack (most recent call first):
>  scripts/cmake/vcpkg_configure_meson.cmake:51 (vcpkg_execute_required_process)
>  ports/libepoxy/portfile.cmake:14 (vcpkg_configure_meson)
>  scripts/ports.cmake:72 (include)
>
>
>Error: Building package libepoxy:x86-windows failed with: BUILD_FAILED
>Please ensure you're using the latest portfiles with `.\vcpkg update`, then
>submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>  Package: libepoxy:x86-windows
>  Vcpkg version: 0.0.82-f2c655c7dfa02fe0fcca4a6207f3f1cc55da540c
>
>Additionally, attach any relevant sections from the log files above.

Please see the attached logs. Let me know if there's any more information I can provide.
[config-x86-windows-rel-err.log.txt](https://github.com/Microsoft/vcpkg/files/1217165/config-x86-windows-rel-err.log.txt)
[config-x86-windows-rel-out.log.txt](https://github.com/Microsoft/vcpkg/files/1217166/config-x86-windows-rel-out.log.txt)

### LINKED ISSUE #1644: error with cmake
The error is happened while me install bzip2 and boost!
I'am not know cmake's Grammar rules。So...you know it!

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: D:/Tools/Cmake/bin/cmake.exe;D:/ThridLibraryPackages/buildtrees/bzip2/src/bzip2-1.0.6;-DBUILD_SHARED_LIBS=ON;-DVCPKG_TARGET_TRIPLET=x86-windows;-DCMAKE_CXX_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP ;-DCMAKE_C_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /MP ;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=D:/ThridLibraryPackages/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DCMAKE_CXX_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi ;-DCMAKE_C_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi ;-DCMAKE_SHARED_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-DCMAKE_EXE_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-G;Ninja;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_INSTALL_PREFIX=D:/ThridLibraryPackages/packages/bzip2_x86-windows
    Working Directory: D:/ThridLibraryPackages/buildtrees/bzip2/x86-windows-rel
    See logs for more information:
      D:\ThridLibraryPackages\buildtrees\bzip2\config-x86-windows-rel-out.log
      D:\ThridLibraryPackages\buildtrees\bzip2\config-x86-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:170 (vcpkg_execute_required_process)
  ports/bzip2/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package bzip2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: bzip2:x86-windows
  Vcpkg version: 0.0.83

### LINKED ISSUE #1660: Failed to install gflags
ENV：
1. vcpkg version bd7cd7f56d5d9fdfeb1f57810a2ea77bf4d7e31a
1. Windows 10 professional, simplified Chinese locale
2. cmake: 3.9.1 c:/Program Files/CMake/
3. git:  2.14.1.windows.1 
4. Installed VS
	- Microsoft Visual Studio Community 2017 15.2 (26430.16) Release
	- Microsoft Visual Studio Community 2015 Version 14.0.25431.01 Update 3
5. I have successfully installed `libevent:x86-windows` and `libevent:x86-windows`, but failed to install gflags.

The output is :

```shell
D:\git\vcpkg>vcpkg install glog gflags
The following packages will be built and installed:
    gflags:x86-windows
    glog:x86-windows
Building package gflags:x86-windows...
-- CURRENT_INSTALLED_DIR=D:/git/vcpkg/installed/x86-windows
-- DOWNLOADS=D:/git/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=D:/git/vcpkg/packages/gflags_x86-windows
-- CURRENT_BUILDTREES_DIR=D:/git/vcpkg/buildtrees/gflags
-- CURRENT_PORT_DIR=D:/git/vcpkg/ports/gflags/.
-- Using cached D:/git/vcpkg/downloads/gflags-gflags-v2.2.0.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch D:/git/vcpkg/ports/gflags/fix-install.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/git/vcpkg/ports/gflags/fix-install.patch done
-- Applying patch D:/git/vcpkg/ports/gflags/fix-static-linking.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/git/vcpkg/ports/gflags/fix-static-linking.patch done
-- Configuring x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;D:/git/vcpkg/buildtrees/gflags/src/gflags-2.2.0;-DGFLAGS_REGISTER_BUILD_DIR:BOOL=OFF;-DGFLAGS_REGISTER_INSTALL_PREFIX:BOOL=OFF;-DBUILD_gflags_nothreads_LIB:BOOL=OFF;-DBUILD_SHARED_LIBS=ON;-DVCPKG_TARGET_TRIPLET=x86-windows;-DCMAKE_CXX_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP ;-DCMAKE_C_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /MP ;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=D:/git/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DCMAKE_CXX_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi ;-DCMAKE_C_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi ;-DCMAKE_SHARED_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-DCMAKE_EXE_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-G;Ninja;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_INSTALL_PREFIX=D:/git/vcpkg/packages/gflags_x86-windows
    Working Directory: D:/git/vcpkg/buildtrees/gflags/x86-windows-rel
    See logs for more information:
      D:\git\vcpkg\buildtrees\gflags\config-x86-windows-rel-out.log
      D:\git\vcpkg\buildtrees\gflags\config-x86-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:170 (vcpkg_execute_required_process)
  ports/gflags/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:72 (include)


Error: Building package gflags:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gflags:x86-windows
  Vcpkg version: 0.0.83-bd7cd7f56d5d9fdfeb1f57810a2ea77bf4d7e31a

Additionally, attach any relevant sections from the log files above.
```

And the content of `D:\git\vcpkg\buildtrees\gflags\config-x86-windows-rel-err.log` is :
```shell
CMake Error at C:/Program Files/CMake/share/cmake-3.9/Modules/CMakeTestCXXCompiler.cmake:44 (message):
  The C++ compiler "C:/Program Files (x86)/Microsoft Visual
  Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX64/x86/cl.exe" is
  not able to compile a simple test program.

  It fails with the following output:

   Change Dir: D:/git/vcpkg/buildtrees/gflags/x86-windows-rel/CMakeFiles/CMakeTmp

  

  Run Build
  Command:"D:/git/vcpkg/downloads/tools/ninja/ninja-1.7.2/ninja.exe"
  "cmTC_81c7a"

  ninja: error: build.ninja:30: loading 'rules.ninja':
  系统找不到指定的文件。


  

  include rules.ninja


                     ^ near here

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:94 (project)



```

### PR DESCRIPTION
**Pull request by Mixaill**
fix #1631 , fix #1644, fix #1660

### CODE REVIEW

File: toolsrc/src/vcpkg.cpp [hunk 1]
```diff
@@ -190,6 +192,9 @@ int wmain(const int argc, const wchar_t* const* const argv)
 {
     if (argc == 0) std::abort();
 
+    _setmode(_fileno(stdin), _O_U16TEXT);
```
Comment (ras0219-msft) [inline toolsrc/src/vcpkg.cpp]: In the docs for `_setmode`[1] it suggests a `_O_U8TEXT` could be used to avoid the conversions inside `print()` et al.

[1] https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setmode

Comment (Mixaill) [inline toolsrc/src/vcpkg.cpp]: `_O_U8TEXT` + no conversion = unhandled exception in `ucrtbase.dll` inside `fputs()` 😦

Comment (Mixaill) [inline toolsrc/src/vcpkg.cpp]: BTW according to https://stackoverflow.com/a/45238837 it is OK to use UTF8 + conversion.

**Comment by Mixaill** [comment]
Looks like `SetConsoleCP()`/`SetConsoleOutputCP()` is what we are looking for.

**Comment by fcharlie** [comment]
Look like gen build.ninja success, OK, I use vcpkg install vcpkg:x64-windows success, cmake 3.9.1 ,chcp is 65001, start a new console, chcp is 936.

**Comment by fcharlie** [comment]
@Mixaill  You can use RIIA to set Console Codepage

```
class CodePageHelper{
  public:
  CodePageHelper(){
   // to UTF8
 }
 ~CodePageHelper(){
   // to raw
  }
};
```

**Comment by Mixaill** [comment]
Added control handler and `atexit()` handler to reset CP.

**Comment by Mixaill** [comment]
@ras0219-msft @alexkaratarakis merge?

**Comment by alexkaratarakis** [comment]
Thanks! Sorry for the delay, we were making some changes around Ctrl+C and vcpkg termination to make sure that the codepage change doesn't leak to the user.
