### PR TITLE
[vcpkg] Use std::filesystem when Visual Studio is greater than 2015

### LINKED ISSUE #9132: Failed to rename files using fs.rename
Dear developers,

I have cloned a repo today and built+configured vcpkg according to the doc of the README provided, which went fine. The problem is that this command `vcpkg install giflib:x86-windows-static` (I launched it from powershell as well as all the prior commands) fails with the following output:
```
Failed to do post-extract rename-in-place.
fs.rename(C:\tools\vcpkg\downloads\tools\powershell-core-6.2.1-windows.partial.2044, C:\tools\vcpkg\downloads\tools\powershell-core-6.2.1-windows, operation not permitted)
```
No additional information about any crashlog is specified.
I'm using Windows 10 Pro 1803, locale: ru_RU

How can I get over this?
Best regards

### PR DESCRIPTION
**Pull request by JackBoosY**
- When the Visual Studio version is 2015, use `std::experimental::filesystem`
- When the Visual Studio version is greater than 2015, use `std::filesystem`

Fixes #9132.

### CODE REVIEW

**Comment by etheory** [comment]
In the process of testing this now, thank you.
It's not building for me.
I get tens of pages of warnings, sorry.
```
warning STL4021: The std::filesystem::u8path() overloads are deprecated in C++20. T
he constructors of std::filesystem::path provide equivalent functionality via construction from u8string, u8string_view, or iterators with value_type char8_t.You can define _SILENCE_CXX20_U8PATH_DEPREC
ATION_WARNING or _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS to acknowledge that you have received this warning. (compiling source file ..\src\vcpkg\vcpkgpaths.cpp) [Z:\Luke\Programming\Graphics\vcpkg2\too
lsrc\vcpkglib\vcpkglib.vcxproj]
```

and many others.

**Comment by strega-nil** [comment]
Yeah, we need to turn off that warning, because that deprecation is not a thing we can deal with rn since we need to work back to VS2015

**Comment by BillyONeal** [comment]
I think this is just another reason to get off std::filesystem.

**Comment by etheory** [comment]
OK, just did a git pull, and it did re-build this time without errors.
Trying now to see if it works when trying to do a package install.
Will report back shortly....

**Comment by etheory** [comment]
So far so good.
The install is currently not giving me any rename or copy errors.
Will keep you posted if I can get all the way to the end of a full install.
Might take a while, but I will let you know.

**Comment by etheory** [comment]
Nope, the dreaded issue is back!

```
PS **\Programming\Graphics\vcpkg2> .\vcpkg.exe install openimageio --triplet x64-windows
Computing installation plan...
A suitable version of cmake was not found (required v3.17.2). Downloading portable cmake v3.17.2...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.17.2/cmake-3.17.2-win32-x86.zip -> **\Programming\Graphics\vcpkg2\downloads\cmake-3.17.2-win32-x86.zip
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> **\Programming\Graphics\vcpkg2\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v5.5.1). Downloading portable nuget v5.5.1...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v5.5.1/nuget.exe -> **\Programming\Graphics\vcpkg2\downloads\22ea847d-nuget.exe
Failed to do post-extract rename-in-place.
fs.rename(**\Programming\Graphics\vcpkg2\downloads\tools\cmake-3.17.2-windows.partial.9060, **\Programming\Graphics\vcpkg2\downloads\tools\cmake-3.17.2-windows, Access is denied.)
```

**Comment by BillyONeal** [comment]
Can you try running it under procmon and see which process is holding the file locked?

**Comment by JackBoosY** [comment]
And can you try to use powershell with admin permission?

**Comment by etheory** [comment]
Could the issue be that I'm working from a network drive?
A friend of mine has suggested that file locking on network drives doesn't work on Windows properly.
Could this be the reason? Should I try again from C:?

**Comment by etheory** [comment]
OK. Somewhat incredibly anticlimactically, this patch isn't required.

The issue is that vcpkg doesn't work with network drives.

I tried again with a fresh vcpkg install on C: and everything worked perfectly.

That's possibly the reason other users are having issues also....

It would be great if it DID work on network drives, but, it doesn't.

**Comment by JackBoosY** [comment]
From network driver... that's we didn't expected.
@BillyONeal What do you think about?

**Comment by BillyONeal** [comment]
Is it both VS2015 and being on a network drive needed to trigger the problem? We intend to remove all `std::experimental` paths when we start shipping binaries, always building `vcpkg.exe` with VS2019.

**Comment by etheory** [comment]
@BillyONeal no, only the location of vcpkg.
I have all VS2019 (I don't use VC2015) installations on C: and was trying to work from a network drive with my code on it.
I installed vcpkg itself, and it's packages to the network location.
That's what fails.

I'm not sure what would happen if both VS2019 AND vcpkg were on the network location, since that's not my use-case.

Moving all my stuff to C: is working perfectly now.

**Comment by Neumann-A** [comment]
>I have all VS2019 (I don't use VC2015) installations on C: and was trying to work from a network drive with my code on it.
I installed vcpkg itself, and it's packages to the network location.

Have you tried `subst`'ing the network drive away?

e.g. `subst N: <networkpath>` but I highly discourage that usage since the linker/compile speed will suffer dramatically due to a lot of small files and network speed etc.

**Comment by etheory** [comment]
> Have you tried `subst`'ing the network drive away?
> 
> e.g. `subst N: <networkpath>` but I highly discourage that usage since the linker/compile speed will suffer dramatically due to a lot of small files and network speed etc.

I already had used subst.
The drive letter was Z: and it mapped to a synology DiskStation, which is normally accessed as \\DiskStation.

And it didn't work with vcpkg.

**Review by strega-nil — CHANGES_REQUESTED** [review]

File: toolsrc/include/vcpkg/base/files.h [hunk 1]
```diff
@@ -2,11 +2,20 @@
 
 #include <vcpkg/base/expected.h>
 #include <vcpkg/base/ignore_errors.h>
+#include <vcpkg/base/pragmas.h>
+
+#include <string.h>
+
```
Comment (BillyONeal) [inline toolsrc/include/vcpkg/base/files.h:8]:
```suggestion
```

Not used

File: toolsrc/src/vcpkg/base/files.cpp [hunk 2]
```diff
@@ -20,6 +20,32 @@
...
+    return fs::path(s.begin(), s.end());
+#endif
+}
+
+std::string fs::u8string(const fs::path& p)
+{
+#if defined(_WIN32)
+    return vcpkg::Strings::to_utf8(p.native());
+#else
+    return p.string();
```
Comment (BillyONeal) [inline toolsrc/src/vcpkg/base/files.cpp:37]: I think this should be `p.native()` since we're making an assumption that it'll be UTF-8.

File: toolsrc/src/vcpkg/base/files.cpp [hunk 3]
```diff
@@ -20,6 +20,32 @@
...
+#endif
+}
+std::string fs::generic_u8string(const fs::path& p)
+{
+#if defined(_WIN32)
+    return vcpkg::Strings::to_utf8(p.generic_wstring());
+#else
+    return p.string();
```
Comment (BillyONeal) [inline toolsrc/src/vcpkg/base/files.cpp:45]: That can't be right, it at least needs to be `generic_string`

File: toolsrc/include/vcpkg/base/files.h [hunk 4]
```diff
@@ -2,11 +2,20 @@
...
+#if !defined(VCPKG_USE_STD_FILESYSTEM) && defined(_MSVC_STL_UPDATE)
+#if _MSVC_STL_UPDATE >= 201803
+// this is for bootstrapping
```
Comment (BillyONeal) [inline toolsrc/include/vcpkg/base/files.h:11]: We should fix the cmake detection script to set this the right way rather than ignoring it here.

Comment (strega-nil) [reply toolsrc/include/vcpkg/base/files.h:11]: huh?

File: toolsrc/include/vcpkg/base/files.h (hunk 1 above)
Comment (strega-nil) [reply toolsrc/include/vcpkg/base/files.h:8]: Yeah, it's used on line 37

Comment (BillyONeal) [reply toolsrc/include/vcpkg/base/files.h:8]: 🤦‍♂️

File: toolsrc/include/vcpkg/base/files.h (hunk 4 above)
Comment (BillyONeal) [reply toolsrc/include/vcpkg/base/files.h:11]: I see, then I think it should be fixed there. Stand by...

**Review by BillyONeal — APPROVED** [review]

**Comment by etheory** [comment]
If you need someone to test this once the PR has stabilized, please let me know!

**Comment by strega-nil** [comment]
@etheory it should be stable now; the one concern I want to fix is getting CMake to support compiling with VS 2015 (so we can continue to test VS2015 even without the VS build system), which will be fixed in a different PR.

**Comment by BillyONeal** [comment]
I see, so it's not just being a network share, it's also a "samba" server. It's possible that they don't implement our attempts to canonicalize the vcpkg root path. :/

**Comment by etheory** [comment]
I'm testing this now....

**Review by ras0219 — APPROVED** [review]

**Review by strega-nil — APPROVED** [review]

**Comment by etheory** [comment]
Should I test this again? As far as I'm aware this PR has been approved but still doesn't fix the issue I'm encountering?

**Comment by strega-nil** [comment]
@etheory unfortunately, there's nothing much we can do if it doesn't fix your issue; `fs::rename` is a straight `MoveFileEx` -- if `MoveFileEx` doesn't work, nothing works.

**Comment by BillyONeal** [comment]
Thanks for your fix Jack!

**Comment by etheory** [comment]
> @etheory unfortunately, there's nothing much we can do if it doesn't fix your issue; `fs::rename` is a straight `MoveFileEx` -- if `MoveFileEx` doesn't work, nothing works.

If that's the case, it might be pertinent to add to the vcpkg documentation that it doesn't work when run on network drives.

**Comment by BillyONeal** [comment]
It does work on network drives, just not those hosted on whatever software this Synology uses.
